name: My .NET Action

on:
  push:
    branches: [ dev ]

env:
  ProjectName: StorageAPI
  IIS_site_name: site.name:$ProjectName
  IIS_pool_name: apppool.name:$ProjectName

jobs:
  build:
    runs-on: self-hosted

    defaults:
      run:
        shell: cmd

    steps:
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
    - name: Stop StorageAPI
      run: |
            %systemroot%\system32\inetsrv\appcmd.exe stop sites /$IIS_site_name
            %systemroot%\system32\inetsrv\appcmd.exe stop apppool /$IIS_pool_name
    - name: Publish Release
      run: dotnet publish StorageAPI.csproj --configuration Release --output "D:\Company (Main2)\.NET core thực hành CI CD\IIS publish"
    - name: Start StorageAPI
      run: |
            %systemroot%\system32\inetsrv\appcmd.exe start sites /$IIS_site_name
            %systemroot%\system32\inetsrv\appcmd.exe start apppool /$IIS_pool_name